### ISSUE TITLE
请问多层的函数嵌套可以处理吗

### ISSUE THREAD

**Issue by Bigbeen** [qddnovo/MathStringExpression#1]
"SUM(2,6,3, SUM(100,SUM(3,4)) + MAX(6,7)”

**Comment by Meterwhite** [comment]
你好，可以的

**Comment by Bigbeen** [comment]
那 SUM 函数怎么定义呢？
 MSFunctionOperator* opFunJS = [MSFunctionOperator operatorWithJSFunction:@"function SUM(a, b){ return a + b; }" error:&errorJSFun];
    [tab setElement:opFunJS];
这样只能带两个参数，不确定个数参数怎么写呢？求指点！

**Comment by Meterwhite** [comment]
恩 这个还做不到解析不定参数

**Comment by Bigbeen** [comment]
@qddnovo 好的  谢了

**Comment by Meterwhite** [comment]
@Bigbeen 你好 现在支持不定参数了.见git首页
