### ISSUE TITLE
为什么在使用JavaScript定义函数的时候计算结果不正确啊？

### ISSUE THREAD

**Issue by lixianhong1992** [qddnovo/MathStringExpression#2]
/**
     *  例4 使用JavaScript定义函数
     */
    NSError* errorJSFun;
    MSFunctionOperator* opFunJS = [MSFunctionOperator operatorWithJSFunction:@"function And(a, b){return a + b;}" error:&errorJSFun];
    [tab setElement:opFunJS];
     NSString* jsExpString = @"And(1,1)";//
    
    BOOL allRight = [MSExpressionHelper helperCheckExpression:jsExpString usingBlock:^(NSError *error, NSRange range) {
        
        NSLog(@"%@",error);
    }];
    
    if(allRight){
        
        //计算表达式
        NSString* computeResult = [MSParser parserComputeExpression:jsExpString error:nil];
        NSLog(@"计算结果为：%@",computeResult);
        
        //表达式转JS表达式
        NSString* jsExpression = [MSParser parserJSExpressionFromExpression:jsExpString error:nil];
        NSLog(@"转JS表达式结果为：%@",jsExpression);
    }

最后输出的计算结果为NAN，表达式为(1,1)

**Comment by Meterwhite** [comment]
你好，问题已经修复，可以点个赞吗……

**Comment by lixianhong1992** [comment]
可以
