### ISSUE TITLE
为什么算除法会崩溃啊？而且不支持小数计算吗？

### ISSUE THREAD

**Issue by Eric1143** [qddnovo/MathStringExpression#3]
![2017-11-28 8 18 41](https://user-images.githubusercontent.com/15024821/33296300-beec5be4-d415-11e7-94c0-09e68092ae8b.png)
![2017-11-28 8 26 52](https://user-images.githubusercontent.com/15024821/33296335-f0d8b1b6-d415-11e7-9478-791695c76e02.png)

**Comment by Meterwhite** [comment]
你好，问题修复了。可以点个赞吗……

**Comment by Eric1143** [comment]
可以，谢谢你

**Comment by Eric1143** [comment]
还有一个问题，算小数怎么保留后面小数点啊

**Comment by Eric1143** [comment]
我测试了，浮点数加减计算会忽略小数
![2017-11-28 7 39 16](https://user-images.githubusercontent.com/15024821/33317969-dffe179c-d473-11e7-8439-7fae9289a884.png)

**Comment by Meterwhite** [comment]
加减法整数的问题修复了，因为之前改动基类，所以这版的问题比较多。确认一下

**Comment by Eric1143** [comment]
好的，谢谢
