### ISSUE TITLE
用js计算会有问题，比如0.3-0.2

### ISSUE THREAD

**Issue by nanys** [qddnovo/MathStringExpression#4]
0.3-0.2=0.09999999999999998

**Comment by Meterwhite** [comment]
得到解决了，可以点个赞吗

**Comment by ywqqqqq** [comment]
@qddnovo 返回结果的类型也是Number类型，为何不一步到位
`NSDecimalNumber *num1 = [NSDecimalNumber decimalNumberWithString:[args[0] stringValue]];
        NSDecimalNumber *num2 = [NSDecimalNumber decimalNumberWithString:[args[1] stringValue]];
        return [num1 decimalNumberByAdding:num2];//@([args[0] doubleValue]+[args[1] doubleValue]); 0.5+0.0005`

**Comment by ywqqqqq** [comment]
@qddnovo 返回结果的类型也是Number类型，为何不一步到位
````
NSDecimalNumber *num1 = [NSDecimalNumber decimalNumberWithString:[args[0] stringValue]]; NSDecimalNumber *num2 = [NSDecimalNumber decimalNumberWithString:[args[1] stringValue]]; return [num1 decimalNumberByAdding:num2];//@([args[0] doubleValue]+[args[1] doubleValue]); 0.5+0.0005
````

**Comment by ywqqqqq** [comment]
@qddnovo 返回结果的类型也是Number类型，为何不一步到位
````
NSDecimalNumber *num1 = [NSDecimalNumber decimalNumberWithString:[args[0] stringValue]];
 
NSDecimalNumber *num2 = [NSDecimalNumber decimalNumberWithString:[args[1] stringValue]]; 

return [num1 decimalNumberByAdding:num2];//@([args[0] doubleValue]+[args[1] doubleValue]); 0.5+0.0005
````

**Comment by qddnovo** [comment]
暂时处理了。可以点个赞吗……


________________________________
发件人: Yan <notifications@github.com>
发送时间: 2018年2月28日 15:48
收件人: qddnovo/MathStringExpression
抄送: Novo; Mention
主题: Re: [qddnovo/MathStringExpression] 用js计算会有问题，比如0.3-0.2 (#4)


@qddnovo<https://github.com/qddnovo> 返回结果的类型也是Number类型，为何不一步到位

NSDecimalNumber *num1 = [NSDecimalNumber decimalNumberWithString:[args[0] stringValue]];

NSDecimalNumber *num2 = [NSDecimalNumber decimalNumberWithString:[args[1] stringValue]];

return [num1 decimalNumberByAdding:num2];//@([args[0] doubleValue]+[args[1] doubleValue]); 0.5+0.0005


―

**Comment by Meterwhite** [comment]
@ywqqqqq 暂时处理了。可以点个赞吗……

**Comment by ywqqqqq** [comment]
@qddnovo 会集成到CocoaPods吗
